/**
 * ogChainService.js
 * Interfaces with the AlphaTrace smart contract on 0G Chain via ethers.js v6.
 */

'use strict'

const { ethers } = require('ethers')
const path = require('path')
const fs = require('fs')

const EXPLORER_BASE = 'https://chainscan-galileo.0g.ai'

// ── Load ABI ─────────────────────────────────────────────────────────────────
function loadABI() {
  // Try local AlphaTrace.json first (generated by deploy script)
  const localPath = path.join(__dirname, '../AlphaTrace.json')
  if (fs.existsSync(localPath)) {
    const data = JSON.parse(fs.readFileSync(localPath, 'utf8'))
    return data.abi
  }

  // Fallback: minimal ABI
  console.warn('[0GChain] AlphaTrace.json not found — using minimal ABI')
  return [
    'function recordDecision(string market, string action, int256 confidence, string reasoning, string storageHash, uint256 entryPrice) returns (uint256)',
    'function getDecision(uint256 id) view returns (tuple(uint256 id, string market, string action, int256 confidence, uint256 timestamp, string reasoning, string storageHash, uint256 entryPrice))',
    'function getLatestDecisions(uint256 count) view returns (tuple(uint256 id, string market, string action, int256 confidence, uint256 timestamp, string reasoning, string storageHash, uint256 entryPrice)[])',
    'function decisionCount() view returns (uint256)',
    'function getTotalPnL() view returns (int256)',
    'event DecisionRecorded(uint256 indexed id, string market, string action, uint256 timestamp, string storageHash)',
    'event TradeSignalEmitted(uint256 indexed decisionId, string market, string action, int256 confidence)',
  ]
}

// ── Lazy-init singletons ─────────────────────────────────────────────────────
let provider = null
let signer = null
let contract = null

/** Returns true only if value looks like a real 0x hex address/key */
function isValidHex(value, minLen = 20) {
  return typeof value === 'string' && /^0x[0-9a-fA-F]+$/.test(value) && value.length >= minLen
}

function getContract() {
  if (!contract) {
    const rpc             = process.env.OG_CHAIN_RPC || 'https://evmrpc.0g.ai'
    const privateKey      = process.env.PRIVATE_KEY
    const contractAddress = process.env.CONTRACT_ADDRESS

    // Detect placeholder values — simulate instead of crashing
    const hasRealAddress = isValidHex(contractAddress, 42)
    const hasRealKey     = isValidHex(privateKey, 66)

    if (!hasRealAddress) {
      console.warn('[0GChain] CONTRACT_ADDRESS is missing or placeholder — chain recording will be simulated')
      return null
    }

    provider = new ethers.JsonRpcProvider(rpc)

    if (!hasRealKey) {
      console.warn('[0GChain] PRIVATE_KEY not set — read-only mode')
      contract = new ethers.Contract(contractAddress, loadABI(), provider)
    } else {
      signer   = new ethers.Wallet(privateKey, provider)
      contract = new ethers.Contract(contractAddress, loadABI(), signer)
    }

    console.log(`[0GChain] Contract loaded at ${contractAddress}`)
  }
  return contract
}


// ── getExplorerUrl ────────────────────────────────────────────────────────────
function getExplorerUrl(txHash) {
  return `${EXPLORER_BASE}/tx/${txHash}`
}

function getAddressUrl(address) {
  return `${EXPLORER_BASE}/address/${address}`
}

// ── recordDecision ────────────────────────────────────────────────────────────
/**
 * Call AlphaTrace.recordDecision() on 0G Chain.
 * @param {Object} decision — full decision object
 * @param {string} storageHash — 0G Storage content hash
 * @returns {Promise<{txHash, decisionId, blockNumber, gasUsed, explorerUrl}>}
 */
async function recordDecision(decision, storageHash) {
  const c = getContract()

  // Simulate if contract not configured
  if (!c || !signer) {
    const fakeId = Math.floor(Math.random() * 10000)
    const fakeTx = '0x' + Array.from({ length: 64 }, () => Math.floor(Math.random() * 16).toString(16)).join('')
    console.warn(`[0GChain] ⚠️  Simulated chain record — txHash: ${fakeTx}`)
    return {
      txHash: fakeTx,
      decisionId: fakeId,
      blockNumber: 0,
      gasUsed: '0',
      explorerUrl: getExplorerUrl(fakeTx),
      simulated: true,
    }
  }

  try {
    // Convert entryPrice: price × 1e8 as uint256
    const entryPriceRaw = BigInt(Math.round((decision.entryPrice || 0) * 1e8))
    const confidenceInt = BigInt(Math.round(Math.max(0, Math.min(100, decision.confidence || 0))))
    const shortReasoning = (decision.shortReasoning || decision.reasoning || '').slice(0, 100)

    const tx = await c.recordDecision(
      decision.market,
      decision.action,
      confidenceInt,
      shortReasoning,
      storageHash,
      entryPriceRaw,
      { gasLimit: 500000n }
    )

    console.log(`[0GChain] Tx submitted: ${tx.hash}`)
    const receipt = await tx.wait()
    console.log(`[0GChain] ✅ Confirmed block: ${receipt.blockNumber} gas: ${receipt.gasUsed}`)

    // Parse DecisionRecorded event to get the ID
    const iface = c.interface
    let decisionId = null
    for (const log of receipt.logs) {
      try {
        const parsed = iface.parseLog(log)
        if (parsed?.name === 'DecisionRecorded') {
          decisionId = Number(parsed.args.id)
          break
        }
      } catch {/* not our event */}
    }

    return {
      txHash: tx.hash,
      decisionId,
      blockNumber: receipt.blockNumber,
      gasUsed: receipt.gasUsed.toString(),
      explorerUrl: getExplorerUrl(tx.hash),
      simulated: false,
    }
  } catch (err) {
    console.error('[0GChain] recordDecision error:', err.message)
    throw err
  }
}

// ── getOnChainDecisions ───────────────────────────────────────────────────────
/**
 * Read latest decisions from the smart contract.
 * @param {number} count
 * @returns {Promise<Object[]>}
 */
async function getOnChainDecisions(count = 10) {
  const c = getContract()
  if (!c) return []

  try {
    const raw = await c.getLatestDecisions(BigInt(count))
    return raw.map((d) => ({
      id: Number(d.id),
      market: d.market,
      action: d.action,
      confidence: Number(d.confidence),
      timestamp: new Date(Number(d.timestamp) * 1000).toISOString(),
      reasoning: d.reasoning,
      storageHash: d.storageHash,
      entryPrice: Number(d.entryPrice) / 1e8,
    }))
  } catch (err) {
    console.error('[0GChain] getOnChainDecisions error:', err.message)
    return []
  }
}

// ── getContractStats ──────────────────────────────────────────────────────────
async function getContractStats() {
  const c = getContract()
  if (!c) return { decisionCount: 0, totalPnL: 0 }

  try {
    const [count, pnl] = await Promise.all([c.decisionCount(), c.getTotalPnL()])
    return { decisionCount: Number(count), totalPnL: Number(pnl) }
  } catch (err) {
    console.warn('[0GChain] getContractStats error:', err.message)
    return { decisionCount: 0, totalPnL: 0 }
  }
}

module.exports = {
  recordDecision,
  getOnChainDecisions,
  getContractStats,
  getExplorerUrl,
  getAddressUrl,
}
